recompense_recompens_homepage:
    path:     /
    defaults: { _controller: RecompenseRecompensBundle:Default:index }
AjouterModele:
        path:     /admin/Ajout
        defaults: { _controller: RecompenseRecompensBundle:Cadeau:ajouter }
AffichageModele:
    path:     /admin/ListModele
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:List }
Delete_Cadeau:
        path:     /admin/Delete/{id}
        defaults: { _controller: RecompenseRecompensBundle:Cadeau:Delete }
Update_Cadeau:
        path:     /admin/Update/{id}
        defaults: { _controller: RecompenseRecompensBundle:Cadeau:Update }
CadeauxModele:
    path:     /ListCadeau
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:Cadeau }
AjouterRecompense:
    path:     /Recompense/{id}
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:Ajout }
RecompenseUser:
    path:     /RecompenseUser
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:Recompense }
AjouterPromo:
    path:     /admin/ajoutpromo
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:AjoutPromo }
DeletePromo:
    path:     /Promo
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:DeletePromo }
CadeauTag:
    path:     /Tag/{id}
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:CadeauTag }
PromoModele:
    path:     /admin/ListPromo
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:ListPromo }
Delete_Promo:
    path:     /admin/DeletePromo/{id}
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:effacerPromo }
hedi:
    path:     /all
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:all }
hed:
    path:     /addmobile/{idcadeau}/{iduser}
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:Addd }
he:
    path:     /mobile/{id}
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:allrec }
h:
    path:     /promo
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:Addpromo }
ha:
    path:     /promo2
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:allpromo }
ham:
    path:     /deletepromo/{coupon}/{iduser}/{total}
    defaults: { _controller: RecompenseRecompensBundle:Cadeau:deletemobile }