<?php

namespace Equipe\EquipeBundle\Repository;

/**
 * FavorisRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FavorisRepository extends \Doctrine\ORM\EntityRepository
{

    function nombreFavoris()
    {
        $query=$this->getEntityManager()->createQuery(
            "select m,count(m.id)  as nb  from EquipeEquipeBundle:Favoris m  GROUP  BY m.idequipe ORDER by nb DESC  "  )
        ;
        return $query->getResult();

    }

}
