<?php
/**
 * Created by PhpStorm.
 * User: Amouri Aziz
 * Date: 11/04/2018
 * Time: 01:32
 */

namespace Equipe\EquipeBundle\Repository;

/**
 * JoueurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

class JoueurRepository extends \Doctrine\ORM\EntityRepository

{

}